workflows:
  production:
    name: Production Build
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: "production"
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build app
        script: |
          npx expo export:web
    artifacts:
      - build/**/*
