workflows:
  production:
    name: Production Mobile Build
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: "production"
        EXPO_TOKEN: $EXPO_TOKEN
        EXPO_PUBLIC_API_URL: $EXPO_PUBLIC_API_URL
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Build Android
        script: |
          eas build --platform android --profile production --non-interactive
    artifacts:
      - build/**/*
